### PR TITLE
fixes for ubuntu 20.04 where opencv has changed

### PR DESCRIPTION
**Pull request by colin-lewis-19**
Compatibility update for running on Focal Fossa

### CODE REVIEW

**Comment by colin-lewis-19** [comment]
credit @DavidMerzJr for 2/3 of these lines

**Comment by colin-lewis-19** [comment]
this should probably be the basis for a fossa-devel branch

**Comment by DavidMerzJr** [comment]
It looks like the kinetic and melodic builds failed due to CUDA version mismatches.  If we merge this to some sort of 20.04_devel, we will probably want to disable the kinetic/melodic build tests.

Edit:  I'm sure some cmake witchery could also be performed to try multiple CUDA versions (10, then 9).  A similar thing could be done for Opencv3/opencv.  The result of the find_package(opencv) could be used to switch between two .cpp files, each giving a different definition of an extern-defined thing.  (Essentially, depending on what you found, link against either a .cpp file containing CV_WINDOW_NORMAL or a .cpp file containing cv::WINDOW_NORMAL).  But that could get messy.

File: yak/CMakeLists.txt [hunk 1]
```diff
@@ -11,7 +11,7 @@ if(NOT DEFINED CMAKE_CUDA_STANDARD)
   set(CMAKE_CUDA_STANDARD_REQUIRED True)
 endif()
 
-find_package(CUDA 9.0 REQUIRED)
```
Comment (schornakj) [inline yak/CMakeLists.txt]: If you increase the minimum CUDA version to 10 then it'll break compatibility with CUDA 9. We need to maintain compatibility with both CUDA 9 and 10, while eventually adding support for CUDA 11. Conceptually there's no reason why CUDA 9 should not work with Ubuntu 20.04.

File: yak/cmake/yak-config.cmake.in [hunk 2]
```diff
@@ -22,7 +22,7 @@ if(NOT TARGET OpenMP::OpenMP_CXX)
 endif()
 
 find_dependency(CUDA 9.0)
-find_dependency(OpenCV 3)
+find_dependency(OpenCV)
```
Comment (schornakj) [inline yak/cmake/yak-config.cmake.in:25]: Looks like this should have been changed [when I was adding compatibility with the Canonical-provided OpenCV version](https://github.com/ros-industrial/yak/commit/845a62a07aed23d3205f463592c67e013c8053c0), which I think is 2.4.

File: yak/src/yak_server.cpp [hunk 3]
```diff
@@ -7,7 +7,7 @@ yak::FusionServer::FusionServer(const kfusion::KinFuParams& params, const Eigen:
   , last_camera_pose_(Eigen::Affine3f::Identity())
 {
   // Debug displays
-  cv::namedWindow("output", CV_WINDOW_NORMAL);
+  cv::namedWindow("output", cv::WINDOW_NORMAL);
```
Comment (schornakj) [inline yak/src/yak_server.cpp:10]: Is `cv::WINDOW_NORMAL` available in both OpenCV 2 and 3?

**Review by schornakj — CHANGES_REQUESTED** [review]

**Comment by schornakj** [comment]
> It looks like the kinetic and melodic builds failed due to CUDA version mismatches. If we merge this to some sort of 20.04_devel, we will probably want to disable the kinetic/melodic build tests.
> 
> Edit: I'm sure some cmake witchery could also be performed to try multiple CUDA versions (10, then 9). A similar thing could be done for Opencv3/opencv. The result of the find_package(opencv) could be used to switch between two .cpp files, each giving a different definition of an extern-defined thing. (Essentially, depending on what you found, link against either a .cpp file containing CV_WINDOW_NORMAL or a .cpp file containing cv::WINDOW_NORMAL). But that could get messy.

CI fails because we're requiring it to find a version of CUDA that isn't installed on the test Docker images. Right now it builds against all combinations of [Xenial, Bionic] and [CUDA 9, CUDA 10]. Proper support for Focal should have it building against all combinations of [Xenial, Bionic, Focal] and [CUDA 9, CUDA 10, CUDA 11].

I've been striving to make it so that a singular version of Yak is able to build in as many different environmental permutations as possible, without requiring switches based on detected library versions.

File: yak/src/yak_server.cpp (hunk 3 above)
Comment (schornakj) [reply yak/src/yak_server.cpp:10]: Looks like this is actually a question of if it's available in OpenCV 2, 3, **and 4**, since it looks like the [Canonical version of OpenCV for Focal is 4.2](https://packages.ubuntu.com/search?keywords=opencv).

Comment (schornakj) [reply yak/src/yak_server.cpp:10]: `WINDOW_NORMAL` is a valid flag for OpenCV [2.4](https://docs.opencv.org/2.4/modules/highgui/doc/user_interface.html#namedwindow), [3.2](https://docs.opencv.org/3.2.0/d7/dfc/group__highgui.html#gabf7d2c5625bc59ac130287f925557ac3), and [4.2](https://docs.opencv.org/4.2.0/d7/dfc/group__highgui.html#gabf7d2c5625bc59ac130287f925557ac3), so this is the right change to make.

Comment (colin-lewis-19) [reply yak/src/yak_server.cpp:10]: > `WINDOW_NORMAL` is a valid flag for OpenCV [2.4](https://docs.opencv.org/2.4/modules/highgui/doc/user_interface.html#namedwindow), [3.2](https://docs.opencv.org/3.2.0/d7/dfc/group__highgui.html#gabf7d2c5625bc59ac130287f925557ac3), and [4.2](https://docs.opencv.org/4.2.0/d7/dfc/group__highgui.html#gabf7d2c5625bc59ac130287f925557ac3), so this is the right change to make.

focal compiles with only changing cv::WINDOW_NORMAL and relaxing the CUDA versioning

File: yak/CMakeLists.txt [hunk 4]
```diff
@@ -11,7 +11,7 @@ if(NOT DEFINED CMAKE_CUDA_STANDARD)
...
+find_package(CUDA REQUIRED)
```
Comment (schornakj) [inline yak/CMakeLists.txt]: I think this should stay as `find_package(CUDA 9.0 REQUIRED)` to keep the same behavior as before. According to the [CMake docs](https://cmake.org/cmake/help/v3.5/command/find_package.html) `find_package` treats the provided library version number as the minimum required version by default, but it'll accept a newer version of the library if one is available.

If we delete the minimum-required version then if someone tries to build using CUDA 8.0 (which isn't supported), they'll get a whole mess of CUDA and C++ compilation errors instead of a message saying "hey your version of CUDA is too old for this package".

**Review by schornakj — CHANGES_REQUESTED** [review]

File: yak/CMakeLists.txt (hunk 4 above)
Comment (colin-lewis-19) [reply yak/CMakeLists.txt]: Understood

**Review by schornakj — APPROVED** [review]
Looks good!
